services:
  back:
    build:
      context: ./back-go
      target: base
    ports:
      - "8080:8080"
    volumes:
      - ./back-go:/app
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - metadict

  front:
    build:
      context: ./front
      target: base
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
    networks:
      - metadict

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/dev-nginx.conf:/etc/nginx/nginx.conf
      - ${TG_BOT_CERT}:${TG_BOT_CERT_SERVER}
      - ${TG_BOT_KEY}:${TG_BOT_KEY_SERVER}
    ports:
      - "8000:443"
    environment:
      - TG_BOT_CERT=${TG_BOT_CERT}
      - TG_BOT_KEY=${TG_BOT_KEY}
    networks:
      - metadict

networks:
  metadict:
    driver: bridge
